import type { Metadata } from "next";
import "./globals.css";
import NavbarWrapper from "@/app/components/navbarWrapper";
import FooterWrapper from "@/app/components/footerWrapper";

export const metadata: Metadata = {
  title: "Loop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarWrapper/>
        {children}
        <FooterWrapper/>
      </body>
    </html>
  );
}
